### ISSUE TITLE
Remove margin-top from panel when it is first-child

### ISSUE THREAD

**Issue by erikhallaraaker** [PayEx/design.payex.com#265]
All panels have `margin-top: 1rem`, which is good as panels usually needs some spacing. It is however, unfortunate that the first child also has this margin, as the panel is usually a direct child of a `col` and that makes it not line up with other content.

I propose to rewrite the panel rule to the following:
```less
.panel {
    &:not(:first-child) {
        margin-top: 1rem;
    }
}
```
